Update update-rusefi-reference.yaml

diff --git a/.github/workflows/update-rusefi-reference.yaml b/.github/workflows/update-rusefi-reference.yaml
--- a/.github/workflows/update-rusefi-reference.yaml
+++ b/.github/workflows/update-rusefi-reference.yaml
@@ -1,12 +1,48 @@
 name: Update rusEFI Reference
 
 on:
-  schedule:
-    - cron: '5 17 * * *' # update rusEFI reference daily at 5:05 pm
-  workflow_dispatch:
+  workflow_call:
 
 jobs:
-  call-workflow-passing-data:
-    uses: rusefi/rusefi/.github/workflows/custom-board-update-rusefi-reference.yaml@master
-    permissions:
-      contents: write
+  update-git:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          ref: release_20240304
+
+      - name: Git Checkout Submodules
+        run: |
+          git submodule update --init --depth=1 ext/rusefi
+
+      - name: Git Update Submodules
+        run: |
+          git submodule update --remote
+
+      - name: Commit fresh submodules
+        env:
+          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
+        run: |
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub git update Action"
+          git add ext/rusefi
+          OUT=$(git commit -am "GHA says update ext/rusefi submodule" 2>&1) || echo "commit failed, finding out why"
+          if echo "$OUT" | grep 'nothing to commit'; then
+            echo "submodule: looks like nothing to commit"
+            echo "NOCOMMIT=true" >> $GITHUB_ENV
+            exit 0
+          elif echo "$OUT" | grep 'changed'; then
+            echo "submodule: looks like something has changed"
+            exit 0
+          else
+            echo "submodule: looks like something unexpected"
+            exit 1
+          fi
+          git status
+
+      - name: Push
+        if: ${{ env.NOCOMMIT != 'true'}}
+        uses: ad-m/github-push-action@master
+        with:
+          github_token: ${{ github.token }}
